//
//  PtpWebcamPtp.h
//  PTP Webcam
//
//  Created by Dömötör Gulyás on 27.07.2020.
//  Copyright © 2020 Doemoetoer Gulyas. All rights reserved.
//

#ifndef PtpWebcamPtp_h
#define PtpWebcamPtp_h

#define PTP_TYPE_COMMAND 0x0001

#define PTP_CMD_GETDEVICEINFO	0x1001
#define PTP_CMD_GETSTORAGEIDS	0x1004
#define PTP_CMD_GETSTORAGEINFO	0x1005
#define PTP_CMD_GETNUMOBJECTS	0x1006
#define PTP_CMD_GETOBJECTHANDLES	0x1007
#define PTP_CMD_GETOBJECTINFO	0x1008
#define PTP_CMD_GETOBJECT		0x1009

#define PTP_CMD_GETPROPDESC		0x1014
#define PTP_CMD_GETPROPVAL		0x1015
#define PTP_CMD_SETPROPVAL		0x1016

#define PTP_CMD_CANON_GETEVFIMG			0x902C
#define PTP_CMD_CANON_GETDEVICEINFO_EX	0x9108
#define PTP_CMD_CANON_SETPROPVAL_EX		0x9110
#define PTP_CMD_CANON_SETREMOTEMODE		0x9114
#define PTP_CMD_CANON_SETEVENTMODE		0x9115
#define PTP_CMD_CANON_GETEVENT			0x9116
#define PTP_CMD_CANON_KEEPDEVICEON		0x911D
#define PTP_CMD_CANON_REQUESTPROPVAL	0x9127
#define PTP_CMD_CANON_GETVIEWFINDERDATA	0x9153
#define PTP_CMD_CANON_DOAF				0x9154
#define PTP_CMD_CANON_DRIVELENS			0x9155
#define PTP_CMD_CANON_DOF_PREVIEW		0x9156
#define PTP_CMD_CANON_AF_CANCEL			0x9160

#define PTP_CMD_NIKON_STARTLIVEVIEW		0x9201
#define PTP_CMD_NIKON_STOPLIVEVIEW		0x9202
#define PTP_CMD_NIKON_GETLIVEVIEWIMG	0x9203

#define PTP_CMD_NIKON_AFDRIVE			0x90C1
#define PTP_CMD_NIKON_DEVICEREADY		0x90C8
#define PTP_CMD_NIKON_GETVENDORPROPS	0x90CA
#define PTP_CMD_NIKON_GETVENDORCODES	0x9439
#define MTP_CMD_GETOBJECTPROPSSUPPORTED	0x9801
#define PTP_CMD_NIKON_MFDRIVE			0x9204
	#define PTP_NIKON_MFDRIVE_CLOSER	0x00000001
	#define PTP_NIKON_MFDRIVE_FARTHER	0x00000002

// Sony get LiveView via GetObject PTP commands
//#define PTP_CMD_SONY_GETLIVEVIEWINFO	0x1008
//#define PTP_CMD_SONY_GETLIVEVIEWIMAGE	0x1009

#define PTP_CMD_SONY_CONNECT			0x9201
#define PTP_CMD_SONY_GETPROPERTIES		0x9202
#define PTP_CMD_SONY_GETPROPDESC		0x9203
#define PTP_CMD_SONY_GETPROPVAL			0x9204
//#define PTP_CMD_SONY_SETSUBPROP			0x9205
//#define PTP_CMD_SONY_SETMAINPROP		0x9207
#define PTP_CMD_SONY_SETPROPABS			0x9205
#define PTP_CMD_SONY_SETPROPSTEP		0x9207
#define PTP_CMD_SONY_GETALLPROPDATA		0x9209

#define PTP_RSP_OK					0x2001
#define PTP_RSP_INCOMPLETETRANSFER	0x2007
#define PTP_RSP_DEVICEBUSY			0x2019
#define PTP_RSP_INVALIDPROPVAL		0x201C
#define PTP_RSP_INVALIDPARAM		0x201D

#define PTP_RSP_CANON_NOT_READY		0xA102

#define PTP_RSP_NIKON_INVALIDSTATUS	0xA004 // eg. Z8 returns this in upload-priority mode
#define PTP_RSP_NIKON_NOTLIVEVIEW	0xA00B


#define PTP_PROP_BATTERYLEVEL		0x5001
#define PTP_PROP_IMAGEQUALITY		0x5003
#define PTP_PROP_WHITEBALANCE		0x5005
#define PTP_PROP_FNUM				0x5007
#define PTP_PROP_FLEN				0x5008
#define PTP_PROP_FOCUSDISTANCE		0x5009
#define PTP_PROP_FOCUSMODE			0x500A
#define PTP_PROP_EXPOSUREMETERING	0x500B
#define PTP_PROP_FLASHMODE			0x500C
#define PTP_PROP_EXPOSURETIME		0x500D
#define PTP_PROP_EXPOSUREPM			0x500E
#define PTP_PROP_EXPOSUREISO		0x500F
#define PTP_PROP_EXPOSUREBIAS		0x5010
#define PTP_PROP_FOCUSMETERING		0x501C

#define PTP_PROP_NIKON_WBTUNE_AUTO			0xD017
#define PTP_PROP_NIKON_WBTUNE_INCADESCENT	0xD018
#define PTP_PROP_NIKON_WBTUNE_FLOURESCENT	0xD019
#define PTP_PROP_NIKON_WBTUNE_SUNNY			0xD01A
#define PTP_PROP_NIKON_WBTUNE_FLASH			0xD01B
#define PTP_PROP_NIKON_WBTUNE_CLOUDY		0xD01C
#define PTP_PROP_NIKON_WBTUNE_SHADE			0xD01D
#define PTP_PROP_NIKON_WB_COLORTEMP			0xD01E
#define PTP_PROP_NIKON_MOVIE_WBTUNE_AUTO		0xD212
#define PTP_PROP_NIKON_MOVIE_WBTUNE_INCADESCENT	0xD213
#define PTP_PROP_NIKON_MOVIE_WBTUNE_FLOURESCENT	0xD215
#define PTP_PROP_NIKON_MOVIE_WBTUNE_SUNNY		0xD216
#define PTP_PROP_NIKON_MOVIE_WBTUNE_CLOUDY		0xD218
#define PTP_PROP_NIKON_MOVIE_WBTUNE_SHADE		0xD219
#define PTP_PROP_NIKON_MOVIE_WB_COLORTEMP		0xD21A
#define PTP_PROP_NIKON_MOVIE_WBTUNE_COLORTEMP	0xD21B
#define PTP_PROP_NIKON_ISOAUTOCONTROL		0xD054
#define PTP_PROP_NIKON_LV_AFMODE			0xD061
#define PTP_PROP_NIKON_ANGLELEVEL			0xD067
#define PTP_PROP_NIKON_ANGLELEVELPITCHING	0xD07D
#define PTP_PROP_NIKON_ANGLELEVELYAWING		0xD07E
#define PTP_PROP_NIKON_ANGLELEVELYAWING		0xD07E
#define PTP_PROP_NIKON_LV_AF				0xD05D
#define PTP_PROP_NIKON_SHUTTERSPEED			0xD100
#define PTP_PROP_NIKON_RECORDINGMEDIA		0xD10B // might be relevant for D90
#define PTP_PROP_NIKON_WBTUNE_AUTOTYPE		0xD141
#define PTP_PROP_NIKON_WBTUNE_FLTYPE		0xD14F
#define PTP_PROP_NIKON_WBTUNE_COLORTEMP		0xD150
#define PTP_PROP_NIKON_ISOAUTOSETTING		0xD16A
#define PTP_PROP_NIKON_LV_APPLYSETTINGS		0xD17B // seems like this is ExposurePreview for newer cameras?
#define PTP_PROP_NIKON_ISOAUTOHIGHLIMIT		0xD183
#define PTP_PROP_NIKON_LV_MODE				0xD1A0
#define PTP_PROP_NIKON_LV_DRIVEMODE			0xD1A1
#define PTP_PROP_NIKON_LV_STATUS			0xD1A2
#define PTP_PROP_NIKON_LV_ZOOM				0xD1A3
#define PTP_PROP_NIKON_LV_PROHIBIT			0xD1A4
#define PTP_PROP_NIKON_LV_EXPOSURE_PREVIEW	0xD1A5
#define PTP_PROP_NIKON_LV_SELECTOR			0xD1A6
#define PTP_PROP_NIKON_LV_WHITEBALANCE		0xD1A7
#define PTP_PROP_NIKON_MOVIE_SHUTTERSPEED	0xD1A8
#define PTP_PROP_NIKON_MOVIE_FNUM			0xD1A9
#define PTP_PROP_NIKON_MOVIE_EXPOSUREBIAS	0xD1AB
#define PTP_PROP_NIKON_LV_IMAGESIZE			0xD1AC
#define PTP_PROP_NIKON_LV_IMAGECOMPRESSION	0xD1BC

#define PTP_PROP_CANON_APERTURE				0xD101
#define PTP_PROP_CANON_EXPOSURETIME			0xD102
#define PTP_PROP_CANON_ISO					0xD103
#define PTP_PROP_CANON_EXPOSUREBIAS			0xD104
#define PTP_PROP_CANON_AUTOEXPOSURE			0xD105
#define PTP_PROP_CANON_METERINGMODE			0xD107
#define PTP_PROP_CANON_FOCUSMODE			0xD108
#define PTP_PROP_CANON_AUTOPOWEROFF			0xD114

#define PTP_PROP_CANON_LV_EYEDETECT			0xD12C
#define PTP_PROP_CANON_LV_CFILTERKIND		0xD137
#define PTP_PROP_CANON_EVF_OUTPUTDEVICE		0xD1B0
#define PTP_PROP_CANON_EVF_MODE				0xD1B1
#define PTP_PROP_CANON_EVF_DOF_PREVIEW		0xD1B2
#define PTP_PROP_CANON_EVF_WHITEBALANCE		0xD1B4
#define PTP_PROP_CANON_EVF_COLORTEMP		0xD1B6
#define PTP_PROP_CANON_EVF_EXPOSURE_PREVIEW	0xD1B7
//#define PTP_PROP_CANON_EVF_ZOOM				0x????
//#define PTP_PROP_CANON_EVF_ZOOMPOSITION		0x????
//#define PTP_PROP_CANON_EVF_ZOOMRECT			0x????
//#define PTP_PROP_CANON_EVF_IMAGEPOSITION		0x????
//#define PTP_PROP_CANON_EVF_COORDINATES		0x????
#define PTP_PROP_CANON_LV_AFMODE			0xD1BA
#define PTP_PROP_CANON_LV_TYPESELECT		0xD1BC
#define PTP_PROP_CANON_FOCUSINFO			0xD1D3

#define PTP_PROP_SONY_IMAGESIZE				0xD203
#define PTP_PROP_SONY_SHUTTERSPEED			0xD20D
#define PTP_PROP_SONY_COLORTEMP				0xD20F
#define PTP_PROP_SONY_WB_GREENMAGENTA		0xD210
#define PTP_PROP_SONY_FOCUSFOUND			0xD213
#define PTP_PROP_SONY_ZOOM					0xD214
#define PTP_PROP_SONY_BATTERYLEVEL			0xD218
#define PTP_PROP_SONY_PICTURE_EFFECT		0xD21B
#define PTP_PROP_SONY_WB_AMBERBLUE			0xD21C
#define PTP_PROP_SONY_ISO					0xD21E
#define PTP_PROP_SONY_LV_STATUS				0xD221
#define PTP_PROP_SONY_AUTOFOCUSBUTTON		0xD2C1
#define PTP_PROP_SONY_SHUTTERBUTTON			0xD2C2


#define PTP_EVENT_DEVICEPROPCHANGED			0x4006
#define PTP_EVENT_DEVICERESET				0x400B

#define PTP_EVENT_CANON_REQESTGETEVENT		0xC101
#define PTP_EVENT_CANON_PROPVALCHANGED		0xC189
#define PTP_EVENT_CANON_AVAILLISTCHANGED	0xC18A
#define PTP_EVENT_CANON_STATUSCHANGED		0xC18B

#define PTP_EVENT_SONY_PROPVALCHANGED		0xC203

typedef enum {
	PTP_DATATYPE_INVALID 		= 0,
	PTP_DATATYPE_SINT8_RAW,
	PTP_DATATYPE_UINT8_RAW,
	PTP_DATATYPE_SINT16_RAW,
	PTP_DATATYPE_UINT16_RAW,
	PTP_DATATYPE_SINT32_RAW,
	PTP_DATATYPE_UINT32_RAW,
	PTP_DATATYPE_SINT64_RAW,
	PTP_DATATYPE_UINT64_RAW,
	PTP_DATATYPE_SINT128_RAW,
	PTP_DATATYPE_UINT128_RAW,
	PTP_DATATYPE_ARRAY_MASK 	= 0x4000,
	PTP_DATATYPE_SINT8_ARRAY,
	PTP_DATATYPE_UINT8_ARRAY,
	PTP_DATATYPE_SINT16_ARRAY,
	PTP_DATATYPE_UINT16_ARRAY,
	PTP_DATATYPE_SINT32_ARRAY,
	PTP_DATATYPE_UINT32_ARRAY,
	PTP_DATATYPE_SINT64_ARRAY,
	PTP_DATATYPE_UINT64_ARRAY,
	PTP_DATATYPE_SINT128_ARRAY,
	PTP_DATATYPE_UINT128_ARRAY,
	PTP_DATATYPE_STRING 		= 0xFFFF, // UCS-2 with 8bit length header
	// the following are nonstandard data types
	// Canon in their wisdom decided all integer types have to be 32bit
	PTP_DATATYPE_EOS_MASK 		= 0x10000,
	PTP_DATATYPE_EOS_SINT8,
	PTP_DATATYPE_EOS_UINT8,
	PTP_DATATYPE_EOS_SINT16,
	PTP_DATATYPE_EOS_UINT16,
	PTP_DATATYPE_EOS_SINT32,
	PTP_DATATYPE_EOS_UINT32,
	PTP_DATATYPE_EOS_STRING 	= PTP_DATATYPE_EOS_MASK + 7, // Canon's null-terminated UTF8 string format
	PTP_DATATYPE_EOS_ARRAY_MASK = PTP_DATATYPE_ARRAY_MASK | PTP_DATATYPE_EOS_MASK,
	PTP_DATATYPE_EOS_SINT8_ARRAY,
	PTP_DATATYPE_EOS_UINT8_ARRAY,
	PTP_DATATYPE_EOS_SINT16_ARRAY,
	PTP_DATATYPE_EOS_UINT16_ARRAY,
	PTP_DATATYPE_EOS_SINT32_ARRAY,
	PTP_DATATYPE_EOS_UINT32_ARRAY,
	PTP_DATATYPE_EOS_STRING_ARRAY = PTP_DATATYPE_EOS_ARRAY_MASK + 7,
} ptpDataType_t;


#endif /* PtpWebcamPtp_h */
